android/src/main/java/com/gantix/JailMonkey/JailMonkeyModule.java

Some android devices always return 'rooted phone' because of canExecuteCommand method. process waitFor functionality added to function.

Android always says that this is a rooted phone

---

android/src/main/java/com/gantix/JailMonkey/JailMonkeyModule.java

This removes both methods (above and below SDK version 23) for detecting root if build tag contains the string `'test-keys'`. It was causing false positives on non-rooted devices whose builds were signed with test-keys.
See https://github.com/GantMan/jail-monkey/issues/18 for more information.

Remove test-keys root check methods

---

JailMonkey/JailMonkey.m

Following React Native upgrade I get the following warning:
```
Module JailMonkey requires main queue setup since it overrides constantsToExport but doesn't implement requiresMainQueueSetup. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.
```
Already applied in _many_ other plugins, like: 
* https://github.com/airbnb/lottie-react-native/pull/226
* https://github.com/luggit/react-native-config/pull/172

React Native 0.52+ requires indication of main queue setup requirements

---

index.js

trustFall is reporting true for a trustable device
`10-13 11:27:22.606 21125 21254 I ReactNativeJS: isJailBroken: false, canMockLocation:false, trustFall:true`
with this fix:
`10-13 11:39:37.035 21125 22603 I ReactNativeJS: isJailBroken: false, canMockLocation:false, trustFall:false`

corrected trustFall

---

android/src/main/java/com/gantix/JailMonkey/MockLocation/MockLocationCheck.java

This fixes #25 as described in the issue.
It would be really great if this could get merged as our app crashes currently on certain OnePlus devices.

Fix NPE when ALLOW_MOCK_LOCATION is missing

---

android/src/main/java/com/gantix/JailMonkey/Rooted/RootedCheck.java

For example, the OnePlus 2’s brand name contains the string `OnePlus` as opposed to `oneplus`.

Compare brand in a case-insensitive manner

---

JailMonkey/JailMonkey.m

OWASP in the MSTG document ( the download can be done here: [https://github.com/OWASP/owasp-mstg/releases/download/1.1-excel/MSTG-EN.pdf](https://github.com/OWASP/owasp-mstg/releases/download/1.1-excel/MSTG-EN.pdf) , 392 is the relevant page ) suggests this list of paths to check (in addition to the existing one) in order to better understand if an iPhone is jailbroken or not.

Expanded file list for the jailbreak test

---

android/src/main/java/com/gantix/JailMonkey/HookDetection/HookDetectionCheck.java
android/src/main/java/com/gantix/JailMonkey/JailMonkeyModule.java

the `hookDetected` method was not visible because it was not set as `static`.
Fixing the issue. Sorry for the inconvenience

the methods should stay static

---

android/src/main/java/com/gantix/JailMonkey/Rooted/RootedCheck.java

Since some manufacturers leave the busybox binary present in the rom, it's better to use [`isRootedWithoutBusyBoxCheck()`](https://github.com/scottyab/rootbeer#false-positives) for all devices rather than specifying certain brands in order to avoid false positives.

Check root without busybox for all devices

---

README.md
android/src/main/java/com/gantix/JailMonkey/MockLocation/MockLocationCheck.java

Looks like the existing check for mocked locations only works for Android version Lollipop and below.  I updated the check to look through current app permissions and check if location can be mocked in any of them.  
This check helps, but still doesn't 100% work.  In the case where the user were to:
1. have a location mocking app
2. set their location
3. delete their app
Their location will still be cached as a mocked location and none of the mocked location apps will be installed.  It really needs to have an additional check in the react native app's location library but since this package isn't tied to a specific location library this really isn't possible.  I added a note in the readme that you should use this check in addition to the `JailMonkey.canMockLocation()` call
fixes: …

Fixed support for android mock location detection on versions Marshmallow and above

---

jailmonkey.d.ts
jailmonkey.js.flow

This PR updates the flow/ts types for several methods that don't return promises resolving to a boolean value but evaluate to return a boolean value directly.
eg. looking at isJailBroken() - the JS wrapper returns a constant value stored in the native code
ie.
````
isJailBroken: () => JailMonkey.isJailBroken
````
which is defined as a constant in native code in Objective-C (sic):
````
JMisJailBronkenKey: @(self.isJailBroken)
````
and in Java:
````
constants.put("isJailBroken", isJailBroken(context));
````
as opposed to isDevelopmentSettingsMode which is defined (only in Java) as a react method that does return a promise.
````
@ReactMethod
public void isDevelopmentSettingsMode(Promise p) {
````
Here we update:
isJailBroken, canMockLocation, trustFall, isOnExternalStorage, AdbEnabled
to all …

Fix flow/ts types for non promise returning methods

---

README.md
android/build.gradle

Looks like the version of [`rootbeer`](https://github.com/scottyab/rootbeer) we're using is quite old (March 2017). So upgrading to the latest version to make sure we're getting the latest root detection on Android.
I'm hoping this will solve some of the false positives I've seen on some Huawei devices. (Possibly related to https://github.com/scottyab/rootbeer/issues/83 )
**Diff:** https://github.com/scottyab/rootbeer/compare/0.0.6...0.0.8

Upgrade rootbeer package to latest (0.0.8)

---

jail-monkey.podspec

`React-Core` is the correct dependency to require for native libs, more information here: https://github.com/facebook/react-native/issues/29633#issuecomment-694187116

Use correct React-Core dependency in podspec - fixes issues with Xcode 12

---

JailMonkey/JailMonkey.m

Currently the library is showing a false positive when it's running on an Apple Silicon as some of the paths are exists on a normal Mac (e.g. /bin/bash).

Disabling jailbreak checks when app is running on Apple Silicon

---

android/src/main/java/com/gantix/JailMonkey/HookDetection/HookDetectionCheck.java
android/src/main/java/com/gantix/JailMonkey/MockLocation/MockLocationCheck.java

Whether there's a root app or xposed/magisk module that prevents us getting packageManager.getInstalledApplications or if the actual OEM's just aren't letting us fetch the information - it appears it just comes back as null on certain devices. I cna't think of any better way to circumvent this crash (Judging by our logs only Samsung devices - several newer note devices and several newer S-series devices.)

Prevent null reference on packageManager.getInstalledApplications

---

JailMonkey/JailMonkey.m

In an effort to keep JailMonkey relevant with newer iOS jailbreaking methods and techniques, update the code with:
- new paths to check
- new symbolic links to check
- new dynamic libraries to check
- new schemes to check
- process forking check
Also sorted the paths lists alphabetically for better readability.
Tested on an iPhone 7 Pro iOS 14.0.1 (Cydia), iPhone 11 Pro Max iOS 14.0.1 (Sileo) and a 5th gen iPad Wifi iPadOS 13.3.1 (Cydia).
Also tested on same devices non-jailbreaked.

Update JailMonkey.m with new checks (paths, symlinks, dylibs, forking)

---

JailMonkey/JailMonkey.m

This was never properly implemented and was just a proxy for `isJailBroken`

iOS simulator mock location check

---

android/build.gradle

Gets the values for build.gradle options from rootProject. Also updated the default values to current react-native version values.
If build.gradle options are different from rootProject it may not build.
#28 
I was getting the same error and the build was failing, because `compileSdkVersion` and `buildToolsVersion` were incompatible.

fix: get build.gradle values from rootProject and update default values

---

android/src/main/java/com/gantix/JailMonkey/JailMonkeyModule.java
android/src/main/java/com/gantix/JailMonkey/Rooted/RootedCheck.java
jailmonkey.d.ts
jailmonkey.js
jailmonkey.js.flow

This is a proposal to deal with issues like https://github.com/GantMan/jail-monkey/pull/102
In our case, we'd like to keep using this lib but keep some granularity on root beer methods, to be able to ignore those that seem to trigger most false positive cases.
Not entirely sure this is the best solution, but it should be retro-compatible (keeping the default `isJailBroken` value) and continues to expose constant values. The caveat is that it still runs all the checks, even the ones we don't use. One way to deal with that would be to completely change the lib behavior and expose async function to execute the detection methods instead of storing them in constants.

Expose android rooted detection methods results to JS

---

jail-monkey.podspec

if you use an old tag, the latest native files get pulled. With this fix, the native files will match the installed version

use right version in podspec

---

android/build.gradle
android/src/main/AndroidManifest.xml
android/src/main/java/com/gantix/JailMonkey/HookDetection/HookDetectionCheck.java

Remove the `package` manifest key to support AGP 8+
This means the library will now only support AGP 7+

Remove `package` name from AndroidManfiest.xml to support AGP 8
