- JailMonkey/JailMonkey.m
Resolves https://github.com/GantMan/jail-monkey/issues/1
> Fixed imports and missing semicolon.

- android/src/main/java/com/gantix/JailMonkey/JailMonkeyModule.java
References https://github.com/GantMan/jail-monkey/issues/7#issuecomment-265235855 and https://github.com/GantMan/jail-monkey/issues/9
> Check rootyness in a way that prevents false positives.

- android/src/main/java/com/gantix/JailMonkey/JailMonkeyModule.java
As opposed to only if all conditions were met... Oops...
> [Android] Fix: isJailbroken() now returns true when any condition is met

- android/src/main/java/com/gantix/JailMonkey/JailMonkeyModule.java
> Fix android

- JailMonkey/JailMonkey.h
- JailMonkey/JailMonkey.m
- jail-monkey.podspec
This PR adds the `jail-monkey.podspec` file to make the library compatible with the Cocoapods integration.
Additionally I have done some code improvements for iOS platform.
> Cocoapod support & code improvements

- .gitignore
- android/build.gradle
- android/src/main/java/com/gantix/JailMonkey/ExternalStorage/ExternalStorageCheck.java
- android/src/main/java/com/gantix/JailMonkey/JailMonkeyModule.java
- android/src/main/java/com/gantix/JailMonkey/MockLocation/MockLocationCheck.java
- android/src/main/java/com/gantix/JailMonkey/Rooted/CheckApiVersion.java
- android/src/main/java/com/gantix/JailMonkey/Rooted/GreaterThan23.java
- android/src/main/java/com/gantix/JailMonkey/Rooted/LessThan23.java
- android/src/main/java/com/gantix/JailMonkey/Rooted/RootedCheck.java
I have added https://github.com/scottyab/rootbeer to the project to enable better jail break detection.
> Added RootBeer for Android detection

- android/src/main/java/com/gantix/JailMonkey/HookDetection/HookDetectionCheck.java
- android/src/main/java/com/gantix/JailMonkey/JailMonkeyModule.java
- index.js
Android now offers the `hookDetected()` methods that tries to understand if there is any dangerous application installed in the phone which can inject malicious code into other applications.
> Added the hookDetection

- JailMonkey/JailMonkey.m
- android/src/main/java/com/gantix/JailMonkey/Debugged/DebuggedCheck.java
- android/src/main/java/com/gantix/JailMonkey/JailMonkeyModule.java
- index.js
`isDebugged()` is a new method which allow the developer to understand if the application is running in debuggable mode or not.
> isDebugged

- .gitignore
- android/build.gradle
- android/src/main/java/com/gantix/JailMonkey/AdbEnabled/AdbEnabled.java
- android/src/main/java/com/gantix/JailMonkey/JailMonkeyModule.java
- android/src/main/java/com/gantix/JailMonkey/JailMonkeyPackage.java
- jailmonkey.d.ts
- jailmonkey.js
- jailmonkey.js.flow
- package.json
*The existing code was improved to return promises every time it is called
*Added the function to know if the device has activated the development function
*Other improvement in general
```
//New  use way  
async componentDidMount() {
// Check if device has development settings enabled
let Dev = await JailMonkey.isDevelopmentSettingsMode()
console.log(Dev) // true or false 
}
```
> Improvement in general

- android/build.gradle
[Rootbeer releases](https://github.com/scottyab/rootbeer/releases)
> Bump rootbeer package to latest (0.0.9)

- ExampleProject/android/app/build.gradle
- ExampleProject/android/app/src/main/AndroidManifest.xml
- android/build.gradle
Closes #85 thanks for the suggestion @jahead
> Bump Android minSdk to 21 inline with React Native 0.64

- ExampleProject/App.js
> Tidy example app

- JailMonkey/JailMonkey.m
- jailmonkey.d.ts
- jailmonkey.js
- jailmonkey.js.flow
To expose the jailbroken message
> Add jailbroken message for iOS

- android/src/main/java/com/gantix/JailMonkey/MockLocation/MockLocationCheck.java
> Reduce tag length for mock location check error to appease lint

- JailMonkey/JailMonkey.m
Update File-based checks with the recommendation from [OWASP](https://github.com/OWASP/owasp-mstg/blob/master/Document/0x06j-Testing-Resiliency-Against-Reverse-Engineering.md#file-based-checks)
> Update File-based Checks

- android/src/main/java/com/gantix/JailMonkey/HookDetection/HookDetectionCheck.java
Added more dangerous packages for better detection. Referenced by [mvt-project ](https://github.com/mvt-project/mvt)
> Added dangerous apps for detection

- android/src/main/java/com/gantix/JailMonkey/Rooted/LessThan23.java
- jailmonkey.js
> Improve handling of missing native module

- JailMonkey/JailMonkey.m
> add detection for dopamine hide-jailbreak

- CHANGELOG.md
- package.json
> chore: bump version to v2.8.1

- android/src/main/java/com/gantix/JailMonkey/HookDetection/HookDetectionCheck.java
> fix: add detection of frida-server process name

- JailMonkey/JailMonkey.m
There are some Tweaks and Apps that enable Location Spoofing and conveniently come with a URL Scheme to query.
> add Location Spoofer URLSchemes
